- .github/workflows/pr-analysis-maven.yml
The workflow logs have a large amount of logging caused by Maven not running in batch mode, in particular the progress indication that spams lines like `Progress (1): 4.1/6.8 kB`.
Run maven commands in batch mode so these lines are not logged.
NO-TICKET
> chore: enable maven batch mode

- .github/workflows/pr-analysis-gradle.yml
- .github/workflows/pr-analysis-maven.yml
The `get-changed-files` Action has an issue which causes the error `The
head commit for this pull_request event is not ahead of the base commit.
Please submit an issue on this action's GitHub repo.` to frequently
occur.
A fork exists which moves this error to a warning to avoid breaking the
workflow.
NO-TICKET
> chore: fix error from modified files step

- .github/workflows/pr-analysis-gradle.yml
- .github/workflows/pr-analysis-maven.yml
The AdoptOpenJDK project has moved and rebranded to Adoptium, with
Temurin being the naming of the JDK binaries produced by the Adoptium
project.
TIS21-SHED
> chore: migrate from adopt to temurin in workflows

- .github/workflows/pr-analysis-gradle.yml
- .github/workflows/pr-analysis-maven.yml
TIS21-SHED
We got warning in sornarcloud for lots of projects: 
`Shallow clone detected during the analysis. Some files will miss SCM information. This will affect features like auto-assignment of issues. Please configure your build to disable shallow clone.`
According to the setup tutorial (step 2): https://sonarcloud.io/project/configuration?id=Health-Education-England_TIS-SYNC&analysisMode=GitHubActions, we should add `fetch-depth: 0` to disable the shallow clones.
> chore:disable shallow clones for Maven PR

- .github/workflows/deploy.yml
Some services are deployed with a service name which does not match the repository name, add an optional `service-name` input which will be used to override the repository name.
The `${service-name}` placeholder should be used in task definition templates.
TIS21-3497
TIS21-3925
> feat: service name override in shared deploy flow

- .github/workflows/deploy.yml
The image to be inserted in to the task definition should still match the repository name, rather than using the service-name override.
TIS21-3497
> fix: use repository name for deploy image

- .github/workflows/ci-cd-gradle.yml
This eases the transition to a more opinionated workflow
TIS21-3874: Rebuild reval maven workflow
> feat: add input for ecs service name

- .github/workflows/pr-analysis-gradle.yml
The default token with customised permissions doesn't have it.
TIS21-3874: Rebuild reval maven workflow
> feat: add read repo content permission

- .github/workflows/build-gradle.yml
- .github/workflows/pr-analysis-gradle.yml
Github Actions workflows can be reran with debugging enabled, this adds some additional logging for the GHA steps themselves by setting the `ACTIONS_RUNNER_DEBUG` env var.
Add an experiemental `--stacktrace` flag to see if we can enable stacktraces for Gradle builds based on the presence of the flag.
TIS21-SHED
> feat: build stacktrace when rerunning with debug

- .github/workflows/build-gradle.yml
- .github/workflows/pr-analysis-gradle.yml
In order to access the private repos in the submodules we need to use the secrets. A new organisation secret has been created for this purpose.
> fix: add submodules secret for esr projects

- .github/workflows/build-gradle.yml
- .github/workflows/pr-analysis-gradle.yml
submodules along with its secret are removed as it is not working for ESR and it is also breaking other repos pipelines.
> fix: revert submodules command

- .github/workflows/deploy.yml
deploy.yml is being used if we do the deployment separately to stage and prod environments. In the ESR services, the deployment will require manual intervention. So the deployment.yml file is required to check submodule availability.
> feat: add submodule and checkout secret

- .github/workflows/build-gradle.yml
- .github/workflows/deploy.yml
- .github/workflows/pr-analysis-gradle.yml
- .github/workflows/pr-analysis-maven.yml
- workflow-templates/maven-pr-workflow.yml
The `id-token: write` permission is required for requesting the OIDC JWT.
TIS21-4862
> fix: add `id-token: write` permissions

- .github/workflows/build-gradle.yml
- .github/workflows/ci-cd-gradle.yml
- .github/workflows/deploy.yml
- workflow-templates/ci-cd-gradle.yml
The `ecr-username` and `ecr-password` workflow secrets can not be removed while in use without breaking calling workflows. Make the secrets optional so the calling workflows can be updated without breakages. Once all callers are updated the secrets can be removed from these reusable workflows.
TIS21-4862
TIS21-4948
> refactor: make ECR username/password optional

- .github/workflows/build-gradle.yml
- .github/workflows/ci-cd-gradle.yml
- .github/workflows/pr-analysis-gradle.yml
- .github/workflows/pr-analysis-maven.yml
- workflow-templates/ci-cd-gradle.yml
- workflow-templates/pr-analysis-gradle.yml
- workflow-templates/pr-analysis-maven.yml
Add a boolean input `use-codeartifact` to replace the codeartifact username and password secrets. The authentication is now done using OIDC so the code artifact user tokens are not required.
The secrets themselves will be removed once all calling workflows have been updated to remove the references.
TIS21-4948
TIS21-4862
> refactor: add `use-codeartifact` flag

- .github/workflows/pr-analysis-maven.yml
> fix: use `use-codeartifact` input for maven setup

- .github/workflows/clear-runs.yml
`${GITHUB_REF#refs/*/}` doesn't seem to work in the quote. Fix by getting current branch with `${{ github.ref_name }}` instead
> fix: getting current branch name

- .github/workflows/ci-cd-gradle.yml
- .github/workflows/clear-runs.yml
The PAT secret only works in the workflow itself, it need to be passed in when it is called as a reusable workflow.
(All our repo that used `ci-cd-gradle.yml` will need to be updated for adding the secrets)
> fix: passing PAT secret to clear-runs workflow

- .github/workflows/build-gradle.yml
- .github/workflows/ci-cd-gradle.yml
- .github/workflows/pr-analysis-gradle.yml
It was tempting to go to a matrix build but walking before running.
I have not done the maven workflows.
Swapping to gradle is as likely to go along with java upgrades.
TIS21-4466: ESR Notification Generator on ECS
> feat: allow overriding the java version

- .github/workflows/deploy.yml
If ECS circuit breaker is enabled for a service the ECS deploy step can give a false successful result, as the triggered rollback is detected as "healthy".
The task definition ARN can be checked against the expectation as a workaround.
See:
https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/191
TIS21-4819
TIS21-5327
> feat: verify deployed task definition

- .github/workflows/pr-analysis-common.yml
The commit linter needs PR read permissions, not content read permissions.
TIS21-SHED
> build: fix PR Analysis - Common permissions

- .github/workflows/pr-analysis-maven.yml
As Sonarcloud's stopped supporting Java 11 since 15 Jan 2024, our new PRs' analysis of Maven project are all blocked. So update Java version is a little urgent.
TIS-SHED
> chore:bump up java version

- .github/workflows/pr-analysis-maven.yml
TCS can no longer download all dependencies inside the  900 seconds token lifetime, bump the token to 1200 seconds.
NO-TICKET
> fix: codeartifact token lifetime

- .github/workflows/auto-version.yml
Update the auto-version workflow to return the new version after incrementing it.
Also add a check to ensure that the version is only incremented when required, based on a tag in the format `v1.2.3`.
NO-TICKET
> feat: return version when auto incrementing

- .github/workflows/auto-version.yml
The auto-version workflow adds a new commit to the main branch, however due to branch protections this is blocked.
Using a PAT with `contents: write` permissions allows the owning user to be configured to ignore the repo's branch protection rules.
NO-TICKET
> feat: require PAT for automated versioning

- .github/workflows/auto-version.yml
`@dwmkerr/standard-version` has been deprecated and is no longer being updated. `commit-and-tag-version` is a drop-in replacement fork, which also includes several fixes.
NO-TICKET
> fix: use latest fork for auto versioning

- .github/workflows/build-gradle.yml
- .github/workflows/pr-analysis-gradle.yml
The `setup-gradle` action is the recommended way to configure GitHub Actions workflows for Gradle.
It takes care of wrapper validation, so the standalone job is no longer needed. It also has more intelligent caching that the `setup-java` action, so the gradle caching should be removed from that step.
Additional benefits include automatic enabling of `--info` and `--stacktrace` flags when the action debug logging is enabled. Generation of a job summary after execution, as well as the ability to publish build scans for easier interrogation and debugging of build issues.
NO-TICKET
> feat: use `setup-gradle` action

- .github/workflows/ci-cd-gradle.yml
The Gradle build scan publishing flag was added to `build-gradle.yml`, but most services call the build via `ci-cd-gradle.yml`. Add the `publish-build-scan` flag to the CI/CD workflow and pass it through when calling the build workflow.
NO-TICKET
> feat: pass build scan flag through CI/CD workflow

- .github/workflows/pr-analysis-maven.yml
No Ticket
The maven pr analysis do not see private repos, hence logs error "repo does not exist with private repos."
The token support should help solve that.
> chore: added support for private repos
